### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by wrobstory** [wrobstory/tumalo#2]
- [ ] Top-level error handling and retry-behavior for requests
- [ ] Per-batch error handling for individual documents where ES returns a failure to index
- [ ] `main` method with command line params for `uberjar`'ing and running remotely
- [ ] Reasonable logging
- [ ] Benchmarks
- [ ] Instructions for running the test suite
